// src/config/permissions.js

export const ROLES = {
  ADMIN: "ADMIN",
  GROWTAG: "GROWTAG",
  FRANCHISE: "FRANCHISE",
  OTHERSHOP: "OTHERSHOP",
  CUSTOMER: "CUSTOMER",
};

export const PERMISSIONS = {

  growtags: {
    view: [ROLES.ADMIN, ROLES.FRANCHISE, ROLES.OTHERSHOP,ROLES.GROWTAG],
    create: [ROLES.ADMIN],
    edit: [ROLES.ADMIN],
    delete: [ROLES.ADMIN],
  },

  assignGrowtags: {
    view: [ROLES.ADMIN,],
    create: [ROLES.ADMIN],
    delete: [ROLES.ADMIN],
  },

  shops: {
    view: [ROLES.ADMIN, ROLES.FRANCHISE, ROLES.OTHERSHOP, ROLES.GROWTAG],
    create: [ROLES.ADMIN],
    edit: [ROLES.ADMIN,ROLES.FRANCHISE,ROLES.OTHERSHOP],
    delete: [ROLES.ADMIN],
  },

  complaints: {
    view: [
      ROLES.ADMIN,
      ROLES.GROWTAG,
      ROLES.FRANCHISE,
      ROLES.OTHERSHOP,
      ROLES.CUSTOMER,
    ],
    create: [ROLES.ADMIN,],
    edit: [ROLES.ADMIN,ROLES.FRANCHISE,ROLES.OTHERSHOP,ROLES.GROWTAG],
    delete: [ROLES.ADMIN],
  },

  customerComplaintSelf: {
    view: [ROLES.CUSTOMER,ROLES.ADMIN],
    create: [ROLES.CUSTOMER],
    edit: [ROLES.CUSTOMER],
    delete: [ROLES.CUSTOMER],
  },

  leads: {
    view: [ROLES.ADMIN,ROLES.FRANCHISE,ROLES.OTHERSHOP,ROLES.GROWTAG],
    create: [ROLES.ADMIN,ROLES.FRANCHISE,ROLES.OTHERSHOP],
    edit: [ROLES.ADMIN,ROLES.FRANCHISE,ROLES.OTHERSHOP],
    delete: [ROLES.ADMIN],
  },

  customers: {
    view: [ROLES.ADMIN, ROLES.FRANCHISE, ROLES.OTHERSHOP, ROLES.GROWTAG],
    create: [ROLES.ADMIN],
    edit: [ROLES.ADMIN],
    delete: [ROLES.ADMIN],
  },

  items: {
    view: [ROLES.ADMIN,ROLES.FRANCHISE,ROLES.GROWTAG,ROLES.OTHERSHOP],
    create: [ROLES.ADMIN,ROLES.FRANCHISE,ROLES.OTHERSHOP,ROLES.GROWTAG],
    edit: [ROLES.ADMIN,ROLES.FRANCHISE,ROLES.OTHERSHOP,ROLES.GROWTAG],
    delete: [ROLES.ADMIN,ROLES.FRANCHISE,ROLES.OTHERSHOP,ROLES.GROWTAG],
  },

  stock: {
    view: [ROLES.ADMIN, ROLES.FRANCHISE, ROLES.OTHERSHOP, ROLES.GROWTAG],
    create: [ROLES.ADMIN],
    edit: [ROLES.ADMIN],
  },

  vendors: {
    view: [ROLES.ADMIN, ROLES.FRANCHISE, ROLES.OTHERSHOP],
    create: [ROLES.ADMIN,ROLES.FRANCHISE,ROLES.OTHERSHOP],
    edit: [ROLES.ADMIN,ROLES.FRANCHISE,ROLES.OTHERSHOP],
    delete: [ROLES.ADMIN],
  },

  purchaseOrders: {
    view: [ROLES.ADMIN, ROLES.FRANCHISE, ROLES.OTHERSHOP, ROLES.GROWTAG],
    create: [ROLES.ADMIN, ROLES.FRANCHISE,ROLES.OTHERSHOP,ROLES.GROWTAG],
    edit: [ROLES.ADMIN,ROLES.FRANCHISE,ROLES.OTHERSHOP,ROLES.GROWTAG],
    delete: [ROLES.ADMIN],
  },

  bills: {
    view: [ROLES.ADMIN, ROLES.FRANCHISE, ROLES.OTHERSHOP, ROLES.GROWTAG],
    create: [ROLES.ADMIN, ROLES.FRANCHISE,ROLES.OTHERSHOP,ROLES.GROWTAG],
    edit: [ROLES.ADMIN, ROLES.FRANCHISE,ROLES.OTHERSHOP,ROLES.GROWTAG],
    delete: [ROLES.ADMIN],
  },

  expenses: {
    view: [ROLES.ADMIN, ROLES.FRANCHISE, ROLES.OTHERSHOP],
    create: [ROLES.ADMIN, ROLES.FRANCHISE,ROLES.OTHERSHOP],
    edit: [ROLES.ADMIN,ROLES.FRANCHISE,ROLES.OTHERSHOP],
    delete: [ROLES.ADMIN],
  },

  invoice: {
    view: [
      ROLES.ADMIN,
      ROLES.GROWTAG,
      ROLES.FRANCHISE,
      ROLES.OTHERSHOP,
      ROLES.CUSTOMER,
    ],
    create: [ROLES.ADMIN, ROLES.FRANCHISE, ROLES.OTHERSHOP],
    edit: [ROLES.ADMIN, ROLES.FRANCHISE, ROLES.OTHERSHOP],
    delete: [ROLES.ADMIN,],
  },

  reports: {
    view: [ROLES.ADMIN, ROLES.GROWTAG, ROLES.FRANCHISE, ROLES.OTHERSHOP],
  },

  quotes: {
    view: [ROLES.ADMIN, ROLES.FRANCHISE, ROLES.OTHERSHOP],
    create: [ROLES.ADMIN, ROLES.FRANCHISE, ROLES.OTHERSHOP],
    edit: [ROLES.ADMIN, ROLES.FRANCHISE, ROLES.OTHERSHOP],
    delete: [ROLES.ADMIN],
  },

};